# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 13 ]
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-java-${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: install
        run: mvn -B install

  native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.3
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: true
      - name: build-native-image
        run: mvn -V verify -Pnative -DskipTests -DskipITs -Dpitest.skip
